# print("Hi, How are you")
# print("hello and welcome to my world")
# print("********Hello*********")
# print("2")
# print("2")
# print("false")
# print("false")
# print("false")
# print("true")
# print("true")
# print("true")
# print("true")
# print("true")
# print("false")
# print("2")
# print("false")
# print("My name is John, I'm 40")
# print("My name isohn, I'm 30")


# print("Name: Harpreet")
# print("Roll no: 2210997092")
# print("Enter PAN no: ABCTY1234D")
# print("Harpreet 2210997092")

print("Enter a string: Harpreet")
print("Enter a character to find: h")
print("The character 'h' is at 0 index")
